halfpipe/pipeline/urls.py
from django.urls import path

from .views import (
    AlignmentView,
    AnnotateView,
    FootprintingView,
    PeakCallingView,
    PipelineCreateView,
    PipelineDeleteView,
    PipelineDetailView,
    PipelineListView,
    PostAlignmentQCView,
    PreAlignmentQCView,
)

app_name = "pipeline"

urlpatterns = [
    path("create", PipelineCreateView.as_view(), name="create"),
    path("list", PipelineListView.as_view(), name="list"),
    path("detail/<int:pk>/delete", PipelineDeleteView.as_view(), name="delete"),
    path("detail/<int:pk>", PipelineDetailView.as_view(), name="detail"),
    path(
        "detail/<int:pk>/pre_alignment_qc",
        PreAlignmentQCView.as_view(),
        name="pre_alignment_qc",
    ),
    path(
        "detail/<int:pk>/alignment",
        AlignmentView.as_view(),
        name="alignment",
    ),
    path(
        "detail/<int:pk>/post_alignment_qc",
        PostAlignmentQCView.as_view(),
        name="post_alignment_qc",
    ),
    path(
        "detail/<int:pk>/peak_calling",
        PeakCallingView.as_view(),
        name="peak_calling",
    ),
    path(
        "detail/<int:pk>/annotate/",
        AnnotateView.as_view(),
        name="annotate",
    ),
    path(
        "detail/<int:pk>/footprinting/",
        FootprintingView.as_view(),
        name="footprinting",
    ),
]

halfpipe/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

from halfpipe.views import IndexView, UploadURlView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="home"),
    path("api/get_presigned_url", UploadURlView.as_view(), name="get_presigned_url"),
    path("api/", include("halfpipe.api.urls")),
    path("pipeline/", include("halfpipe.pipeline.urls")),
    path("diff_analysis/", include("halfpipe.differential.urls")),
    path("login", LoginView.as_view(), name="login"),
    path(
        "logout",
        LogoutView.as_view(),
        name="logout",
    ),
]

halfpipe/pipeline/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.utils.translation import gettext as _

from halfpipe.fields import FileUploadField, SequenceField
from halfpipe.models import Assembly
from halfpipe.validators import validate_even
from halfpipe.widgets import FileUploadWidget

FASTQ_INPUT_ATTRS = {"accept": ".fastq,.fastq.gz,text/plain,chemical/seq-na-fastq"}
BAM_INPUT_ATTRS = {"accept": ".bam"}


class PresetForm(forms.Form):
    PRESET_NAMES = (
        ("normal", _("Normal")),
        ("strict", _("Strict")),
        ("lax", _("Lax")),
    )

    preset = forms.ChoiceField(
        choices=PRESET_NAMES,
        required=False,
        help_text=_("Select a preset for specific filtering needs."),
    )


class PipelineForm(forms.Form):
    """Provides the main form for pipeline creation."""

    note = forms.CharField(
        max_length=50,
        required=False,
        help_text=_("Short description of the pipeline for identification purposes."),
    )

    send_email = forms.BooleanField(
        initial=False,
        required=False,
        help_text=_("Sends a notification via email when the pipeline finished."),
    )

    # General * non biological * pipeline settings
    retain_user_uploaded = forms.BooleanField(
        initial=False,
        required=False,
        help_text=_(
            "Saves the files uploaded to this form. If you mix multiple Pipelines"
            " this helps to keep track of the input data."
        ),
    )

    # General pipeline settings
    assembly = forms.ModelChoiceField(
        queryset=Assembly.objects.all(),
        label=_("Assembly"),
        help_text=_(
            "Choose the reference assembly to be used to process the given reads."
        ),
    )

    enable_paired_end = forms.BooleanField(
        initial=True,
        required=False,
        help_text=_("Enable for paired end data."),
    )

    forward_readfile_url = FileUploadField(
        label=_("Forward read file"),
        required=False,
        help_text=_("Forward readfile."),
        widget=FileUploadWidget(FASTQ_INPUT_ATTRS),
    )

    reverse_readfile_url = FileUploadField(
        label=_("Reverse read file"),
        required=False,
        help_text=_("Reverse readfile."),
        widget=FileUploadWidget(FASTQ_INPUT_ATTRS),
    )

    readfile_url = FileUploadField(
        label=_("Read file"),
        required=False,
        help_text=_("Readfile."),
        widget=FileUploadWidget(FASTQ_INPUT_ATTRS),
    )

    # Pre alignment processing
    enable_adapter_trimming = forms.BooleanField(
        initial=True,
        required=False,
        help_text=_("Enables trimming of adapters that are left from sequencing."),
    )

    detect_adapters = forms.BooleanField(
        initial=True,
        required=False,
        help_text=_("Autodetect the used adapters."),
    )
    forward_adapter_sequence = SequenceField(
        max_length=200,
        required=False,
        help_text=_("Forward adapter sequence."),
    )
    reverse_adapter_sequence = SequenceField(
        max_length=200,
        required=False,
        help_text=_("Reverse adapter sequence."),
    )
    adapter_sequence = SequenceField(
        max_length=200,
        required=False,
        help_text=_("Adapter sequence in this field."),
    )

    # Post alignment processing
    enable_unpaired_filter = forms.BooleanField(initial=True, required=False)
    enable_unproperly_paired_filter = forms.BooleanField(
        required=False,
        help_text=_(
            "To be properly paired, a mapped read has to be paired with a mate mapping "
            "on the complementary strand of the same chromosome in a reasonable "
            "distance. Improperly paired reads do not satisfy all criteria."
        ),
    )
    enable_mate_unmapped_filter = forms.BooleanField(required=False)
    enable_unmapped_filter = forms.BooleanField(initial=True, required=False)
    enable_nonprimary_filter = forms.BooleanField(
        initial=True,
        required=False,
        help_text=_(
            "A non-primary (secondary) alignment occurs when a read maps "
            "decently well to multiple locations on the genome."
        ),
    )
    enable_supplementary_filter = forms.BooleanField(
        initial=True,
        required=False,
        help_text=_(
            "A supplementary is read that does not map linearly along the "
            "chromosome."
        ),
    )

    enable_quality_filter = forms.BooleanField(
        initial=True,
        required=False,
        help_text=_(
            "If quality filter is enabled, all reads with a MAPQ score smaller "
            "than the given threshold get discarded."
        ),
    )
    quality_threshold = forms.IntegerField(
        required=False,
        validators=[MinValueValidator(0)],
        initial=10,
        help_text=_(
            "Typical thresholds for Bowtie2 alignment are 10 (less conservative), 20, "
            "or 30 (more conservative). The highest possible MAPQ score in a Bowtie2 "
            "alignment is 42."
        ),
    )

    enable_mitochondrial_filter = forms.BooleanField(
        initial=True,
        required=False,
        help_text=_(
            "If mitochondrial filter is enabled, all reads mapped to the "
            "mitochondrial genome get discarded. Filtering unmapped reads prior "
            "is mandatory."
        ),
    )

    enable_duplicated_filter = forms.BooleanField(
        initial=True,
        required=False,
        help_text=_(
            "Duplicates can occur during library construction (PCR) or "
            "during sequencing (optical)."
        ),
    )

    enable_shift_filter = forms.BooleanField(
        initial=False,
        required=False,
        help_text=_(
            "Only recommended if the exact position of motifs is needed while "
            "processing ATAC-seq data, since the sequence and quality scores "
            "are trimmed during the shifting."
        ),
    )

    # Peak Calling:
    control_bam_file = forms.BooleanField(
        initial=False,
        required=False,
        help_text=_(
            "The control is reducing the number of false peaks (exist as a background)"
            " when used with the treated sample."
        ),
    )

    control_file_url = FileUploadField(
        label=_("Control file (Background)"),
        required=False,
        widget=FileUploadWidget(BAM_INPUT_ATTRS),
    )

    use_fdr_cutoff = forms.BooleanField(
        initial=True,
        required=False,
        label=_("Use FDR cutoff"),
        help_text=_("Use FDR-value as cutoff instead of a p-value."),
    )

    # pvalue Pvalue cutoff for peak detection.
    p_value_cutoff = forms.FloatField(
        initial=0.05,
        validators=[MinValueValidator(0)],
        required=False,
        help_text=_(
            "P value cutoff for peak detection. If pvalue cutoff is set, qvalue will "
            "not be calculated and reported as -1 in the final result"
        ),
    )

    # oder qvalue Minimum FDR (q-value) cutoff for peak detection.
    minimum_fdr_cutoff = forms.FloatField(
        initial=0.05,
        validators=[MinValueValidator(0)],
        required=False,
        help_text=_(
            "Minimum false discovery rate (q-value) cutoff for peak detection."
        ),
    )

    # Effective genome size default hs
    exact_genome_size = forms.BooleanField(
        initial=False,
        required=False,
        help_text=_("Specific genome size for, otherwise the given organism is used."),
    )

    genome_size = forms.IntegerField(
        label=_("Genome size in Mbp"),
        initial=270,
        validators=[MinValueValidator(1)],
        required=False,
        help_text=_("Insert the exact genome size in million base pairs."),
    )

    # Footprinting:
    calculate_footprint_scores = forms.BooleanField(
        initial=True,
        required=False,
        help_text=_("Select to calculate footprint scores with HINT."),
    )
    build_genome_tracks = forms.BooleanField(
        initial=False,
        required=False,
        help_text=_("Select to build a genomic profile for visualization."),
    )
    find_matching_motifs = forms.BooleanField(
        initial=True,
        required=False,
        help_text=_(
            "Select to perform motif matching for footprints (source: JASPAR)."
        ),
    )
    build_seq_profiles = forms.BooleanField(
        initial=True,
        required=False,
        help_text=_(
            "Select to generate profiles to inspect Chromatin accessability"
            "around binding sites for TFs."
        ),
    )

    max_number_of_plots = forms.IntegerField(
        initial=4,
        required=False,
        help_text=_(
            "Choose EVEN maximum number of profile-around-motif plots. Will only "
            "show the sequencing profiles around the n most appearing motifs."
        ),
        validators=[MinValueValidator(0), validate_even],
    )

    NUM = "num"
    BITSCORE = "bit"
    MOTIF_RANKING_CHOICES = [
        (NUM, "Number of occurences of motif"),
        (BITSCORE, "BitScore of single motif appearances"),
    ]
    motif_ranking = forms.ChoiceField(choices=MOTIF_RANKING_CHOICES, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def remove(self, cleaned_data, to_remove):
        """Removes given values in `to_remove` from `cleaned_data`."""

        for remove in to_remove:
            # Sanity checking
            if cleaned_data.get(remove):
                del cleaned_data[remove]

    def handle_field_dependencies(self, cleaned_data, needed_fields, to_remove=[]):
        """Checks if all given fields exist, and throws an error if not.

        Unneeded fields are removed.
        """
        for field in needed_fields:
            if not cleaned_data.get(field[0]):

halfpipe/pipeline/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormView

from halfpipe.models import (
    Alignment,
    Annotate,
    Footprinting,
    PeakCalling,
    Pipeline,
    PostAlignmentQC,
    PreAlignmentQC,
)
from halfpipe.pipeline.forms import PipelineForm, PresetForm
from halfpipe.pipeline.process import run_pipeline
from halfpipe.serializers import PipelineDetailSerializer
from halfpipe.views import ProcessDeleteView

PRESETS = {
    "normal": {},  # Normal uses initial value from fields in the form.
    "strict": {
        "enable_unproperly_paired_filter": True,
        "enable_mate_unmapped_filter": True,
        "quality_threshold": 30,
        # "enable_shift_filter": True, # TODO: Reenable
        "minimum_fdr_cutoff": 0.025,
    },
    "lax": {
        "quality_threshold": 10,
        # "enable_shift_filter": True, # TODO: Reenable
        "minimum_fdr_cutoff": 0.075,
    },
}


class PipelineCreateView(LoginRequiredMixin, FormView):
    """Creates a new pipeline and queues it for processing."""

    form_class = PipelineForm
    template_name = "pipeline/create.html"
    success_url = "/pipeline/list"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Append preset form to context
        context["preset_form"] = self.preset_form

        return context

    def get_initial(self):
        # Use preset from url if present
        preset = self.request.GET.get("preset", "normal")
        self.preset_form = PresetForm({"preset": preset})

        if self.preset_form.is_valid():
            return PRESETS[self.preset_form.cleaned_data["preset"]].copy()
        else:
            return {}

    def form_valid(self, form):
        options = form.cleaned_data

        # The instance can't be serialized, and we don't want to break existing api
        assembly = options.pop("assembly_instance")
        note = options.pop("note", "")

        pipeline = Pipeline.objects.create(
            options=options,
            pre_alignment_qc=PreAlignmentQC.objects.create(),
            alignment=Alignment.objects.create(),
            post_alignment_qc=PostAlignmentQC.objects.create(),
            peak_calling=PeakCalling.objects.create(),
            annotate=Annotate.objects.create(),
            footprinting=Footprinting.objects.create(),
            assembly=assembly,
            note=note,
            user=self.request.user,
        )

        # Start the pipeline job
        run_pipeline.apply_async(countdown=5, args=[options, pipeline.pk])

        return super().form_valid(form)


class PipelineListView(ListView):
    """Lists all created pipelines."""

    model = Pipeline
    paginate_by = 25
    template_name = "pipeline/list.html"
    ordering = ["-creation_date"]


class PipelineDeleteView(ProcessDeleteView):
    model = Pipeline
    success_url = "pipeline:list"


class PipelineDetailView(DetailView):
    model = Pipeline
    template_name = "pipeline/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Inject serialized pipeline for use in js
        # The same serializer is used for the detailed websocket updates
        context["pipeline_data"] = PipelineDetailSerializer(context["object"]).data

        return context


class PreAlignmentQCView(PipelineDetailView):
    template_name = "pipeline/pre_alignment_qc.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Saving some typing.
        # Would be available as `object.pre_alignment_qc.fastp_report`
        context["pre_alignment_qc"] = context["object"].pre_alignment_qc.fastp_report
        return context


class AlignmentView(PipelineDetailView):
    template_name = "pipeline/alignment.html"


class PostAlignmentQCView(PipelineDetailView):
    template_name = "pipeline/post_alignment_qc.html"


class PeakCallingView(PipelineDetailView):
    template_name = "pipeline/peak_calling.html"


class AnnotateView(PipelineDetailView):
    template_name = "pipeline/annotate.html"


class FootprintingView(PipelineDetailView):
    template_name = "pipeline/footprinting.html"

halfpipe/pipeline/templates/pipeline/alignment.html
{% extends "pipeline/detail.html" %}
{% load i18n %}
{% load static %}

{% block step_detail %}
<h2>{% trans "Mapping Statistics" %}</h2>
{% if object.alignment.status == "SUCCESS" %}
<div class="accordion mb-3" id="accordionInfo">
  <div class="accordion-item">
    <h2 class="accordion-header" id="infoHeader">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#infoContent">
        <b>{% trans "Additional information" %}</b>
      </button>
    </h2>
    <div id="infoContent" class="accordion-collapse collapse" data-bs-parent="#accordionInfo">
      <div class="accordion-body">
        {% blocktranslate %}
        <b>Bowtie 2</b><br>
        For Mapping, the tool Bowtie 2 is used. Bowtie 2 is a fast and memory-efficient tool for aligning sequencing reads to long reference sequences.
        In a first step, Bowtie 2 indexes the reference genome based on a Burrows-Wheeler Transformation. In a second step, the reads are aligned.
        Bowtie 2 is able to align paired-end reads as well as unpaired reads. <br>
        {% endblocktranslate %}
        {% if object.options.enable_paired_end %}
        {% blocktranslate %}
        <b>Paired-end Alignment</b><br>
        A pair that aligns with the expected relative mate orientation and with the expected range of distances between mates is said to align "concordantly".
        If both mates have unique alignments, but the alignments do not match paired-end expectations (i.e. the mates aren't in the expected relative orientation, or aren't within the expected distance range, or both),
        the pair is said to align "discordantly". Discordant alignments may be of particular interest, for instance, when seeking structural variants.<br>
        If Bowtie 2 cannot find a paired-end alignment for a pair, by default it will go on to look for unpaired alignments for the constituent mates. <br>
        {% endblocktranslate %}
        {% endif %}
        {% blocktranslate %}
        <b>Valid Alignments</b><br>
        Bowtie 2 only maps valid alignments. An alignment is considered as valid if its alignment score is no less than a minimum score threshold.
        The score threshold depends i.a. on the read length. When a read has multiple alignments, it means that a read has multiple alignments that are valid and distinct from one another,
        so the same read can be validly mapped to different places.<br>
        <b>Procedure</b><br>
        By default, Bowtie 2 searches for distinct, valid alignments for each read. When it finds a valid alignment, it generally will continue to look for alignments that are nearly as good or better.
        It will eventually stop looking, when it has enough information to report an alignment. Please have in mind that Bowtie 2
        does not guarantee that the reported alignment is the best regarding the alignment score!<br>
        For further information see:
        <a href="http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#alignment-summary">bowtie2_manual</a> <br>
        {% endblocktranslate %}
      </div>
    </div>
  </div>
</div>

<div class="card mb-3">
  <h4 class="card-header">
    {% trans "Summary" %}
  </h4>
  <div class="card-body">


    {% if object.options.enable_paired_end %}
    <table class="table">
      <tbody>
        <tr>
          <th>{% trans "Total number of read pairs"  %}</th>
          <th>{{ object.alignment.all_reads }}</th>
        </tr>
        <tr>
          <td>{% trans "Number of valid read pairs" %}</td>
          <td>{{ object.alignment.valid_reads}}</td>
        </tr>
        <tr>
          <td>{% trans "Reads that aligned concordantly exactly 1 time" %}</td>
          <td>{{ object.alignment.exactly_one_align }}</td>
        </tr>
        <tr>
          <td>{% trans "Reads that aligned concordantly >1 times" %}</td>
          <td>{{ object.alignment.more_than_one}}</td>
        </tr>
        <tr>
          <td>{% trans "Reads that aligned condordantly 0 times" %}</td>
          <td>{{ object.alignment.zero_aligned_reads }}</td>
        </tr>
        <tr>
          <td>{% trans "Reads that only aligned disconcordantly" %}</td>
          <td>{{ object.alignment.discord_aligned_reads}}</td>
        </tr>
        <tr>
          <td>{% trans "Reads that aligned neither concordantly nor disconcordantly" %}</td>
          <td>{{ object.alignment.never_aligned_reads}}</td>
        </tr>
        <tr>
          <td>{% trans "Reads where only one mate aligned" %}</td>
          <td>{{ object.alignment.only_one_mate_aligned }}</td>
        </tr>
        <tr>
          <td>{% trans "Reads where no mate aligned" %}</td>
          <td>{{ object.alignment.no_mate_aligned }}</td>
        </tr>
        <tr>
          <td class="fw-bold">{% trans "Overall alignment rate" %}</td>
          <td class="fw-bold">{{ object.alignment.overall_alignment_rate }}% </td>
        </tr>
      </tbody>
    </table>
    {% else %}
    <table class="table">
      <tbody>
        <tr>
          <th>{% trans "Total number of reads"  %}</th>
          <th>{{ object.alignment.all_reads }}</th>
        </tr>
        <tr>
          <td>{% trans "Number of unpaired reads" %}</td>
          <td>{{ object.alignment.valid_reads}}</td>
        </tr>
        <tr>
          <td>{% trans "Reads that aligned 0 times" %}</td>
          <td>{{ object.alignment.zero_aligned_reads }}</td>
        </tr>
        <tr>
          <td>{% trans "Reads that aligned exactly 1 time" %}</td>
          <td>{{ object.alignment.exactly_one_align }}</td>
        </tr>
        <tr>
          <td>{% trans "Reads that aligned >1 times" %}</td>
          <td>{{ object.alignment.more_than_one}}</td>
        </tr>
        <tr>
          <td class="fw-bold">{% trans "Overall alignment rate" %}</td>
          <td class="fw-bold">{{ object.alignment.overall_alignment_rate }}% </td>
        </tr>
      </tbody>
    </table>
    {% endif %}
  </div>
</div>


<div class="card mb-3">
  <h4 class="card-header">
    {% trans "Plots" %}
  </h4>
  <div class="card-body">
    <!-- <img class="img-fluid mx-auto d-block" src="{{ object.alignment.analysis_plot.url }}"> -->
    <div class="col-12">
      <canvas id="bowtie2_data"/>
    </div>
  </div>
</div>
<script src="{% static "extern/js/chartjs.min.js" %}"></script>
<script src="{% static "js/alignment.js" %}"></script>
{% else %}
{% include "snippets/messages.html" with messages=object.alignment.messages.all %}
{% endif %}
{% endblock step_detail %}

halfpipe/pipeline/templates/pipeline/annotate.html
{% extends "pipeline/detail.html" %}
{% load i18n %}
{% load static %}

{% block step_detail %}
<h2>{% trans "Peak annotate" %}</h2>
  {% if object.annotate.status == "SUCCESS" %}
    <div class="card mb-3">
      <h4 class="card-header">
        {% trans "Peak distribution and region" %}
      </h4>
      <div class="card-body">
        <div class="row">
          <div class="col-md-6">
            <img class="img-fluid" src="{{ object.annotate.covplot.url }}">
          </div>
          <div class="col-md-6">
            <img class="img-fluid" src="{{ object.annotate.upset.url }}">
          </div>
        </div>
      </div>
    </div>

    <div class="card mb-3">
      <h4 class="card-header">
        {% trans "Frequency and heatmap" %}
      </h4>
      <div class="card-body">
        <div class="row">
          <div class="col-md-4">
            <img class="img-fluid" src="{{ object.annotate.heatmap.url }}">
          </div>
          <div class="col-md-8">
            <img class="img-fluid" src="{{ object.annotate.avgplot.url }}">
          </div>
        </div>
      </div>
    </div>


    {% if object.annotate.over_representation %}
      <div class="card mb-3">
        <h4 class="card-header">
          {% trans "KEGG" %}
        </h4>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <img class="img-fluid" src="{{ object.annotate.over_representation.url }}">
            </div>
            <div class="col-md-6">
              <img class="img-fluid" src="{{ object.annotate.gene_set_enrichment.url }}">
            </div>
          </div>
        </div>
      </div>

      <div class="card mb-3">
        <h4 class="card-header">
          {% trans "Gene set enrichment details" %}
        </h4>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <img class="img-fluid" src="{{ object.annotate.upset_enriched.url }}">
            </div>
            <div class="col-md-6">
              <img class="img-fluid" src="{{ object.annotate.cnet.url }}">
            </div>
          </div>
        </div>
      </div>
    {% else %}
      <div class="card mb-3">
        <h4 class="card-header">
          {% trans "KEGG" %}
        </h4>
        <div class="card-body">
          {% trans "No data available." %}
        </div>
      </div>
    {% endif %}
    {% else %}
      {% include "snippets/messages.html" with messages=object.annotate.messages.all %}
  {% endif %}
{% endblock step_detail %}

halfpipe/pipeline/templates/pipeline/footprinting.html
{% extends "pipeline/detail.html" %}
{% load i18n %}
{% load static %}

{% block step_detail %}
    <h2>{% trans "Footprinting" %}</h2>
    {% if object.footprinting.status == "SUCCESS" %}
        <div class="card mb-3">
            <h4 class="card-header">
                {% trans "Overview" %}
            </h4>
            <div class="card-body">
                <h5>{% trans "Summary" %}</h5>
                <table class="table">
                    <thead>
                    <tr>
                        <th>{% trans "Category" %}</th>
                        <th>{% trans "Number" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>{% trans "Reads" %}</td>
                        <td>{{ object.footprinting.num_reads }}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Peaks" %}</td>
                        <td>{{ object.footprinting.num_peaks }}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Tag counts within peaks" %}</td>
                        <td>{{ object.footprinting.num_tc_within_peaks }}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Footprints" %}</td>
                        <td>{{ object.footprinting.num_footprints }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        {% include "snippets/footprints.html" with plots=object.footprinting.plots.all %}
    {% else %}
      {% include "snippets/messages.html" with messages=object.footprinting.messages.all %}
    {% endif %}
{% endblock step_detail %}

halfpipe/pipeline/templates/pipeline/list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Pipelines" %}{% endblock title %}

{% block content %}
<h1>{% trans "Pipelines" %}</h1>
<p>
<a href="{% url "pipeline:create" %}">{% trans "Create new pipeline" %}</a>
</p>

{% if object_list %}
<div class="table-responsive">
  <table class="table" id="pipeline_table">
    <thead>
      <tr>
        <th>{% trans "ID" %}</th>
        <th>{% trans "Status" %}</th>
        <th>{% trans "Assembly information" %}</th>
        <th>{% trans "Creation date" %}</th>
        <th>{% trans "Note" %}</th>
        <th>{% trans "Actions" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for pipeline in object_list %}
      <tr id="pipeline_{{ pipeline.pk }}">
        <td>{{ pipeline.pk }}</td>
        <td><span>{{ pipeline.status }}</span></td>
        <td>{{ pipeline.assembly }}</td>
        <td>{{ pipeline.creation_date|date:"c" }}</td>
        <td>{{ pipeline.note }}</td>
        <td><a href="{% url "pipeline:detail" pk=pipeline.pk %}">{% trans "Detail" %}</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<script src="{% static "js/update_pipeline_list.js" %}"></script>
{% else %}
{% trans "No pipelines" %}
{% endif %}


{% include "snippets/pagination.html" %}
{% endblock content %}

halfpipe/pipeline/templates/pipeline/preset.html
{% load i18n %}
<form autocomplete="off">
  {% include "snippets/field.html" with field=form.preset %}
</form>

<div class="modal fade" id="confirmedSelectModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{% trans "Confirmation required" %}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="{% trans "Close" %}"></button>
      </div>
      <div class="modal-body">
        {% blocktrans %}
          All data you entered will be lost if changing the preset, are you sure you want to continue?
        {% endblocktrans %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans "Close" %}</button>
        <form method="get">
          <input hidden name="preset" id="confirmedSelectChange" />
          <button class="btn btn-danger">{% trans "Continue" %}</button>
        </form>
      </div>
    </div>
  </div>
</div>