halfpipe/differential/urls.py
from django.urls import path

from .views import (
    ChipView,
    DifferentialCreateView,
    DifferentialDeleteView,
    DifferentialDetailView,
    DifferentialListView,
    HintView,
)

app_name = "differential"

urlpatterns = [
    path("list", DifferentialListView.as_view(), name="list"),
    path("create", DifferentialCreateView.as_view(), name="create"),
    path("detail/<int:pk>/delete", DifferentialDeleteView.as_view(), name="delete"),
    path("detail/<int:pk>", DifferentialDetailView.as_view(), name="detail"),
    path(
        "detail/<int:pk>/hint",
        HintView.as_view(),
        name="footprinting",
    ),
    path(
        "detail/<int:pk>/chip",
        ChipView.as_view(),
        name="annotation",
    ),
]

halfpipe/pipeline/urls.py
from django.urls import path

from .views import (
    AlignmentView,
    AnnotateView,
    FootprintingView,
    PeakCallingView,
    PipelineCreateView,
    PipelineDeleteView,
    PipelineDetailView,
    PipelineListView,
    PostAlignmentQCView,
    PreAlignmentQCView,
)

app_name = "pipeline"

urlpatterns = [
    path("create", PipelineCreateView.as_view(), name="create"),
    path("list", PipelineListView.as_view(), name="list"),
    path("detail/<int:pk>/delete", PipelineDeleteView.as_view(), name="delete"),
    path("detail/<int:pk>", PipelineDetailView.as_view(), name="detail"),
    path(
        "detail/<int:pk>/pre_alignment_qc",
        PreAlignmentQCView.as_view(),
        name="pre_alignment_qc",
    ),
    path(
        "detail/<int:pk>/alignment",
        AlignmentView.as_view(),
        name="alignment",
    ),
    path(
        "detail/<int:pk>/post_alignment_qc",
        PostAlignmentQCView.as_view(),
        name="post_alignment_qc",
    ),
    path(
        "detail/<int:pk>/peak_calling",
        PeakCallingView.as_view(),
        name="peak_calling",
    ),
    path(
        "detail/<int:pk>/annotate/",
        AnnotateView.as_view(),
        name="annotate",
    ),
    path(
        "detail/<int:pk>/footprinting/",
        FootprintingView.as_view(),
        name="footprinting",
    ),
]

halfpipe/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

from halfpipe.views import IndexView, UploadURlView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="home"),
    path("api/get_presigned_url", UploadURlView.as_view(), name="get_presigned_url"),
    path("api/", include("halfpipe.api.urls")),
    path("pipeline/", include("halfpipe.pipeline.urls")),
    path("diff_analysis/", include("halfpipe.differential.urls")),
    path("login", LoginView.as_view(), name="login"),
    path(
        "logout",
        LogoutView.as_view(),
        name="logout",
    ),
]

halfpipe/differential/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.utils.translation import gettext as _

from halfpipe.fields import PipelineMultiSelectField
from halfpipe.models import Pipeline


class MotifFilterForm(forms.Form):
    name = forms.CharField(max_length=200, required=False)
    p_value = forms.FloatField(
        initial=0.05,
        min_value=0,
        max_value=1,
        required=False,
        label=_("p-value cutoff"),
    )
    include_no_plot = forms.BooleanField(required=False, initial=False)


class DiffForm(forms.Form):
    send_email = forms.BooleanField(
        initial=False,
        required=False,
        help_text=_("Sends a notification via email when the pipeline finished."),
    )

    note = forms.CharField(
        max_length=50,
        required=False,
        help_text=_(
            "Short description of the differential analysis "
            "for identification purposes."
        ),
    )

    pipelines = PipelineMultiSelectField(label=_("Pipelines"))
    cluster = forms.IntegerField(
        label=_("Cluster size"),
        help_text=_("Cluster size used for KEGG analysis."),
        validators=[MinValueValidator(1)],
        initial=5,
    )

    enable_bias_correction = forms.BooleanField(
        label=_("Enable bias correction"),
        help_text=_("Enables bias correction for footprint analysis."),
        initial=True,
        required=False,
    )

    def clean_pipelines(self):
        field = self.cleaned_data["pipelines"]
        data = Pipeline.objects.filter(pk__in=field["pipelines"])

        if data.count() < 2:
            self.add_error(
                "pipelines", ValidationError(_("At least two pipelines are required."))
            )

        return data

halfpipe/differential/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormView

from halfpipe.differential.forms import DiffForm, MotifFilterForm
from halfpipe.differential.process import run_differential_analysis
from halfpipe.models import DiffAnalysis, DiffChip, DiffHint, Motif
from halfpipe.serializers import DiffAnalysisDetailSerializer
from halfpipe.views import ProcessDeleteView


class DifferentialListView(ListView):
    """Lists all created differential analysis."""

    model = DiffAnalysis
    paginate_by = 25
    template_name = "differential/list.html"
    ordering = ["-creation_date"]


class DifferentialCreateView(LoginRequiredMixin, FormView):
    """Creates a new differential analysis"""

    form_class = DiffForm
    template_name = "differential/create.html"
    success_url = "/diff_analysis/list"

    def form_valid(self, form):
        options = form.cleaned_data

        pipelines = options.pop("pipelines")
        note = options.pop("note", "")
        with transaction.atomic():
            analysis = DiffAnalysis.objects.create(
                options=options,
                diff_hint=DiffHint.objects.create(),
                diff_chip=DiffChip.objects.create(),
                user=self.request.user,
                note=note,
            )

            analysis.pipelines.set(pipelines)

            # Hack to trigger websocket update via signals after m2m change.
            # We should use a different signal for that.
            analysis.save()

            run_differential_analysis.apply_async(
                countdown=5, args=[options, analysis.pk]
            )

        return super().form_valid(form)


class DifferentialDetailView(DetailView):
    model = DiffAnalysis
    template_name = "differential/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["differential_data"] = DiffAnalysisDetailSerializer(
            context["object"]
        ).data

        return context


class DifferentialDeleteView(ProcessDeleteView):
    model = DiffAnalysis
    success_url = "differential:list"


class HintView(ListView):
    template_name = "differential/hint.html"
    model = Motif
    paginate_by = 50
    context_object_name = "motifs"

    def get_queryset(self):
        self.differential = get_object_or_404(DiffAnalysis, pk=self.kwargs.get("pk"))

        qs = self.differential.diff_hint.motifs.order_by("p_values__0")

        self.form = MotifFilterForm(self.request.GET)
        if self.form.is_valid():
            cleaned_data = self.form.cleaned_data
            if not any(bool(v) for v in cleaned_data.values()):
                cleaned_data = {"name": None, "p_value": 0.05, "include_no_plot": False}
                self.form = MotifFilterForm(initial={})

            if name := cleaned_data.pop("name"):
                qs = qs.filter(name__icontains=name)

            if p_value := cleaned_data.pop("p_value"):
                qs = qs.filter(p_values__0__lte=p_value)

            if not cleaned_data.pop("include_no_plot"):
                qs = qs.filter(lineplot__isnull=False)

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["differential_data"] = DiffAnalysisDetailSerializer(
            self.differential
        ).data

        context["object"] = self.differential
        context["form"] = self.form
        return context


class ChipView(DifferentialDetailView):
    template_name = "differential/chip.html"

halfpipe/differential/templates/differential/chip.html
{% extends "differential/detail.html" %}
{% load i18n %}
{% load static %}

{% block step_detail %}
    <h2>{% trans "CHIPSeeker Details" %}</h2>
    {% if object.diff_chip.status == "SUCCESS" %}
        <div class="card mb-3">
            <h4 class="card-header">
                {% trans "Peak distribution relative to transcription starting sites (TSS)" %}
            </h4>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <figure>
                            <img class="img-fluid" src="{{ object.diff_chip.heatmap.url }}">
                            <figcaption>{% trans "Heatmap: Peak distribution relative to TSS (peaks sorted by peak quality from top to bottom)" %}</figcaption>
                        </figure>
                    </div>
                    <div class="col-md-8">
                        <figure>
                            <img class="img-fluid" src="{{ object.diff_chip.avgplot.url }}">
                            <figcaption>{% trans "Peak count frequency distribution" %}</figcaption>
                        </figure>

                    </div>
                </div>
            </div>
        </div>
        <div class="card mb-3">
            <h4 class="card-header">
                {% trans "Feature information" %}
            </h4>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <img class="img-fluid" src="{{ object.diff_chip.annobar.url }}">
                    </div>
                    <div class="col-md-6">
                        <img class="img-fluid" src="{{ object.diff_chip.dist_to_tss.url }}">
                    </div>
                </div>
            </div>
        </div>

    {% if object.diff_chip.dotplot %}
      <div class="card mb-3">
        <h4 class="card-header">
          {% trans "Differential gene set enrichment analysis" %}
        </h4>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
                <figure>
                    <img class="img-fluid" src="{{ object.diff_chip.dotplot.url }}">
                    <figcaption>{% trans "KEGG pathway enrichment analysis" %}</figcaption>
                </figure>
            </div>
            <div class="col-md-6">
                <figure>
                    <img class="img-fluid" src="{{ object.diff_chip.vennplot.url }}">
                    <figcaption>{% trans "Overlap of peaks and annotated genes" %}</figcaption>
                </figure>
            </div>
          </div>
        </div>
      </div>
    {% else %}
      <div class="card mb-3">
        <h4 class="card-header">
          {% trans "Differential gene set enrichment analysis" %}
        </h4>
        <div class="card-body">
          {% trans "No data available." %}
        </div>
      </div>
    {% endif %}
    {% else %}
      {% include "snippets/messages.html" with messages=object.diff_chip.messages.all %}
    {% endif %}
{% endblock step_detail %}

halfpipe/differential/templates/differential/create.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Run new differential analysis" %}{% endblock title %}

{% block content %}
  <h1>{% trans "Run new differential analysis" %}</h1>

  <form method="post" autocomplete="off">
    {% csrf_token %}

    {% include "snippets/large_field.html" with field=form.pipelines %}

    <div class="card mb-3">
      <div class="card-header">
        {% trans "General options" %}
      </div>
      <div class="card-body">
        {% include "snippets/field.html" with field=form.send_email %}

        {% include "snippets/field.html" with field=form.note %}

        {% include "snippets/field.html" with field=form.enable_bias_correction %}
        {% include "snippets/field.html" with field=form.cluster %}
      </div>
    </div>

    <input id="formSubmit" class="btn btn-primary my-3 float-end" type="submit" value="{% trans "Save" %}">
  </form>
{% endblock content %}

halfpipe/differential/templates/differential/detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Differential Analysis Details" %}{% endblock title %}

{% block content %}
  {{ differential_data|json_script:"differential_data" }}

  <div class="m-0 row align-items-center justify-content-between">
    <h1 class="p-0" style="width: initial;">{% trans "Differential Analysis Detail" %}</h1>
    {% if request.user.is_superuser or request.user == object.user %}
      {% include "snippets/delete_confirm.html" with view="differential:delete" %}
    {% endif %}
  </div>

  <ul class="mb-3 p-2 border rounded-1 bg-light list-inline">
    <li class="list-inline-item">
      {% include "snippets/icon.html" with name="clock" %}<span>{{ object.creation_date }}</span>
    </li>
    <li class="list-inline-item">
      {% comment %} Get's filled with js {% endcomment %}
      {% include "snippets/icon.html" with name="hourglass" %}<span class="duration" id="duration"></span>
    </li>
    <li class="list-inline-item">
      {% include "snippets/icon.html" with name="bug" %}
      <span>{{ object.get_assembly.organism.name }} - {{ object.get_assembly.name }}</span>
    </li>
    <li class="list-inline-item">
      {% include "snippets/icon.html" with name="info-circle" %}<span>{{ object.pk }}</span>
    </li>
    {% if object.note %}
    <li class="list-inline-item">
      {% include "snippets/icon.html" with name="sticky" %}<span>{{ object.note }}</span>
    </li>
    {% endif %}

    <li class="list-inline-item">
      <span id="status">{{ object.status }}</span>
    </span>
  </ul>

  <div class="row mb-3">
    {% trans "HINT Analysis" as title %}
    {% include "snippets/step_card.html" with step=object.diff_hint name="diff_hint" view="differential:footprinting" %}
    {% trans "CHIPSeeker" as title %}
    {% include "snippets/step_card.html" with step=object.diff_chip name="diff_chip" view="differential:annotation" %}
  </div>

  {% include "snippets/file_view.html" %}

  <div class="accordion mb-3" id="accordionInfo">
    <div class="accordion-item">
      <h2 class="accordion-header" id="infoHeader">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#infoContent">
          <b>{% trans "Pipelines" %}</b>
        </button>
      </h2>
      <div id="infoContent" class="accordion-collapse collapse" data-bs-parent="#accordionInfo">
        <div class="accordion-body">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>{% trans "Pipeline" %}</th>
                  <th>{% trans "Note" %}</th>
                </tr>
              </thead>
              <tbody>
                {% for pipeline in object.pipelines.all %}
                <tr>
                  <td>
                    <a href="{% url "pipeline:detail" pk=pipeline.pk %}">Pipeline {{ pipeline.pk }}</a>
                  </td>
                  <td>{{ pipeline.note }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script src="{% static "js/update_differential_detail.js" %}"></script>

  {% block step_detail %}
  {% endblock step_detail %}

{% endblock content %}

halfpipe/differential/templates/differential/hint.html
{% extends "differential/detail.html" %}
{% load i18n %}
{% load static %}

{% block step_detail %}
  <h2>{% trans "HINT Analysis Details" %}</h2>
  {% if object.diff_hint.status == "SUCCESS" %}
    <div class="card">
      <h4 class="card-header">
        {% trans "Overview" %}
      </h4>
      <div class="card-body">
        <div class="row">
          {% for plot in object.diff_hint.scatter_plots.all %}
          {% if object.pipelines.count > 2 %}
            <div class="col-12 col-md-6">
          {% else %}
            <div class="col-12">
          {% endif %}
            <img class="img-fluid" src="{{ plot.url }}">
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    {% comment %}Needed to leave margin to top for page anchor. {% endcomment %}
    <div id="motifs"></div>
    <div class="card my-3">
      <h4 class="card-header">
        {% trans "Plots" %}
      </h4>
      <div class="card-body">
        <h5>{% trans "Seq profiles around binding sites" %}</h5>

        <div class="row">
          {% trans "Search" as search %}
          {% include "snippets/forms.html" with form=form method="get" submit_text=search %}
        </div>

        <div class="row">
          <div class="table-responsive">
            <table class="table table-sm">
              <thead>
                <tr>
                  <th>{% trans "Motif name" %}</th>
                  <th>{% trans "External ressources" %}</th>
                  <th>{% trans "max P value" %}</th>
                  <th>{% trans "Action" %}</th>
              </thead>
              <tbody>
                {% for motif in motifs %}
                <tr>
                  <td><small>{{ motif.name }}</small></td>
                  <td><small>
                      <a href="{{ motif.get_url_jaspar }}">{% trans "JASPAR" %}</a>
                      <a href="{{ motif.get_url_uniprot }}">{% trans "UniProt" %}</a>
                  </small></td>
                  <td><small>{{ motif.p_values|first|floatformat:4 }}</small></td>
                  <td>
                    <button
                      class="btn btn-primary btn-sm"
                      type="button"
                      {% if motif.lineplot %}
                        data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}"
                      {% else %}
                        disabled
                      {% endif %}
                    >
                      {% trans "Show" %}
                    </button>
                  </td>
                </tr>
                {% if motif.lineplot %}
                  <tr>
                    <td colspan="3" style="padding: 0; border: none;">
                      <div class="row justify-content-center collapse" id="collapse{{ forloop.counter }}">
                        <img class="img-fluid" src="{{ motif.lineplot.url }}">
                      </div>
                    </td>
                  </tr>
                {% endif %}
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        {% include "snippets/pagination.html" with append="#motifs" %}
      </div>
    </div>
  {% else %}
    {% include "snippets/messages.html" with messages=object.diff_hint.messages.all %}
  {% endif %}
{% endblock step_detail %}

halfpipe/differential/templates/differential/list.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Differential Analysis" %}{% endblock title %}

{% block content %}
<h1>{% trans "Differential Analysis" %}</h1>
<p>
<a href="{% url "differential:create" %}">{% trans "Run new differential analysis" %}</a>
</p>

{% if object_list %}
<div class="table-responsive">
  <table class="table" id="diffTable">
    <thead>
      <tr>
        <th>{% trans "ID" %}</th>
        <th>{% trans "Status" %}</th>
        <th>{% trans "Pipeline count" %}</th>
        <th>{% trans "Assembly" %}</th>
        <th>{% trans "Creation date" %}</th>
        <th>{% trans "Note" %}</th>
        <th>{% trans "Actions" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for analysis in object_list %}
        <tr id="diff_{{ analysis.pk }}">
          <td>{{ analysis.pk }}</td>
          <td><span>{{ analysis.status }}</span></td>
          <td>{{ analysis.pipelines.count }}</td>
          <td>{{ analysis.get_assembly }}</td>
          <td>{{ analysis.creation_date|date:"c" }}</td>
          <td>{{ analysis.note }}</td>
          <td><a href="{% url "differential:detail" pk=analysis.pk %}">{% trans "Detail" %}</a></td>
        </tr>
     {% endfor %}
    </tbody>
  </table>
</div>


<script src="{% static "js/update_differential_list.js" %}"></script>
{% else %}
{% trans "No data found." %}
{% endif %}

{% include "snippets/pagination.html" %}
{% endblock content %}